horoeka-2019/flatwarming

- client/components/App.jsx
- client/components/Nav.jsx
A simple menu component with register, log in, and home button links. The register and login pages conditionally render based on which button is clicked.
> create nav component

- knexfile.js
- migrations/20191205000806_users.js
- migrations/20191205122820_rubbishUsers.js
- migrations/20191205123056_rubbishPlan.js
- migrations/20191205123326_expense.js
- migrations/20191205123618_jobs.js
- migrations/20191205123811_flatmates.js
- seeds/0-users.js
- seeds/1-flatmates.js
- seeds/2-rubbishUsers.js
- seeds/3-rubbishPlan.js
- seeds/4-expense.js
- seeds/5-jobs.js
> create tables of database

- client/actions/nav-buttons.js
- client/components/Nav.jsx
- client/reducers/index.js
- client/reducers/logout-button.js
- package-lock.json
- package.json
We need an actual dashboard page to check that this works but should be allgood!
> Create log out button

- client/reducers/reg-button.js
- tests/client/reducers/nav-buttons.test.js
> 30 test nav button reducers

- package.json
yeet
run 'npm run db:reset' to delete the dev.sqlite file, re-run migrations and re-run seeds.
> db:reset script is working

- client/components/RegisterFlatDetails.jsx
improve registration-detail-ui
> improve ui

- client/components/LogIn.jsx
> loggin in makes the login and register buttons dissappear woopwoop

- client/actions/flatmate.action.js
- client/components/App.jsx
- client/components/Register.jsx
- client/components/RegisterFlatDetails.jsx
- client/reducers/flatmate.reducer.js
- server/db/users.js
Please merge to Dev. Fix issue when we merged last time. Some codes is missing...
> fix merge issue

- client/actions/error.js
- client/actions/flatmateDetails.action.js
- client/components/Names.jsx
- client/components/Power.jsx
- client/components/RegisterFlatDetails.jsx
- client/reducers/error.js
- client/reducers/flatmateDetails.reducer.js
- client/reducers/index.js
Please help review it. Thanks.
> 79 add flatmate action and reducer

- client/components/RegisterFlatDetails.jsx
> fixed redirect to dashboard page after register flat details is submitted

- client/components/App.jsx
- client/components/Dashboard.jsx
- client/components/Internet.jsx
- client/components/Power.jsx
- client/components/Water.jsx
- package-lock.json
- package.json
Hey, we could countdown days, hours, minutes now.
> add moment to calculate countdown time by days, hours, minutes, seconds

- client/components/Dashboard.jsx
bug is fixed. Please review it. Thanks.
> fix 115-page is refreshed the list disappears

- client/components/Dashboard.jsx
Please review it. Countdown time is correct now. Thanks.
> fix countdown issue

- client/actions/flatmates.action.js
- client/actions/user.js
- client/api/flatmates.js
- client/components/App.jsx
- client/components/Jobs.jsx
- client/components/LogIn.jsx
- client/components/Nav.jsx
- client/components/Setting.jsx
- client/reducers/flatmates.reducer.js
- client/reducers/index.js
- client/reducers/user.js
- server/db/users.js
- server/routes/users.js
Hi, 
Setting works, Please have a review it. Thanks.
> 137 setting component and functionalities

- client/components/App.jsx
Fix typo in RegisterFlatFetails to RegisterFlatDetails
> Fix typo in RegisterFlatDetails

- client/api/flatmates.js
- client/api/jobs.js
- client/api/registerFlatDetails.js
I reverted the apiURL's to the original "http://localhost:3000/api/v1/users" so it works again!
> revert apiURL's to localhost

- client/components/Internet.jsx
- client/components/Names.jsx
- client/components/Register.jsx
- client/components/Setting.jsx
- client/components/WelcomeText.jsx
fix issue that undefined userId for setting page after register. Please review and merge it
> fix issue that setting undefined after register

- client/actions/flatmates.action.js
- client/components/Dashboard.jsx
> fix show error issue

- client/components/Nav.jsx
- client/components/Setting.jsx
fix issue that sometimes show previous user details, please review it.
> fix issue that sometimes show previous user detail

- client/components/Jobs.jsx
- tests/server/db.test.js
- tests/server/routes.test.js
added 5 basic test cases. Pleaser review it. Thanks.
> add 5 basic test cases
